jobs:
- job: Build
  displayName: 'Build'
  timeoutInMinutes: 120
  pool:
    vmImage: macos-13

  variables:
    platform: ${{ parameters.platform }}
    arch: ${{ parameters.arch }}
    xcodeVersion: ${{ '14.3.1' }}

  steps:
  - script: |
      sudo xcode-select -s /Applications/Xcode_$(xcodeVersion).app
      sh build.sh $(platform) $(arch)
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: 'angle/angle.tar.gz'
      ArtifactName: '$(platform).$(arch)'
      publishLocation: Container
