jobs:
- job: Build
  displayName: 'Build'
  timeoutInMinutes: 120
  pool:
    vmImage: macos-13

  variables:
    platform: ${{ parameters.platform }}
    arch: ${{ parameters.arch }}
    xcodeVersion: ${{ '15.2' }}

  steps:
  - script: |
      TO_REPLACE="Xcode.app"
      NEW_STRING="Xcode_$(xcodeVersion).app"
      sed -ie "s#${TO_REPLACE}#${NEW_STRING}#g" *.gn
    displayName: 'Replace Strings'

  - script: |
      sudo xcode-select -s /Applications/Xcode_$(xcodeVersion).app
      chmod +x build.sh
      chmod +x bundle_in_framework.sh
      chmod +x generate_info_plist.sh
      chmod +x create_egl_headers.sh
      chmod +x create_glesv2_headers.sh
      ./build.sh $(platform) $(arch)
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: 'angle/angle.tar.gz'
      ArtifactName: '$(platform).$(arch)'
      publishLocation: Container
