jobs:
- job: Build
  displayName: 'Build'
  timeoutInMinutes: 120
  pool:
    vmImage: macos-13

  variables:
    xcodeVersion: ${{ '15.2' }}

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download iOS Artifacts'
    inputs:
      artifactName: 'iOS.arm64'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download iOS Simulator (arm64) Artifacts'
    inputs:
      artifactName: 'Simulator.arm64'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download iOS Simulator (x64) Artifacts'
    inputs:
      artifactName: 'Simulator.x64'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download visionOS Artifacts'
    inputs:
      artifactName: 'VisionOS.arm64'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download visionOS Simulator (arm64) Artifacts'
    inputs:
      artifactName: 'VisionOSSimulator.arm64'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download visionOS Simulator (x64) Artifacts'
    inputs:
      artifactName: 'VisionOSSimulator.x64'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download Mac (arm64) Artifacts'
    inputs:
      artifactName: 'Mac.arm64'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download Mac (x64) Artifacts'
    inputs:
      artifactName: 'Mac.x64'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download Catalyst (arm64) Artifacts'
    inputs:
      artifactName: 'Catalyst.arm64'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download Catalyst (x64) Artifacts'
    inputs:
      artifactName: 'Catalyst.x64'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - script: |
      sudo xcode-select -s /Applications/Xcode_$(xcodeVersion).app
      tar -xzvf iOS.arm64/angle.tar.gz
      tar -xzvf Simulator.arm64/angle.tar.gz
      tar -xzvf Simulator.x64/angle.tar.gz
      tar -xzvf VisionOS.arm64/angle.tar.gz
      tar -xzvf VisionOSSimulator.arm64/angle.tar.gz
      tar -xzvf VisionOSSimulator.x64/angle.tar.gz
      tar -xzvf Mac.arm64/angle.tar.gz
      tar -xzvf Mac.x64/angle.tar.gz
      tar -xzvf Catalyst.arm64/angle.tar.gz
      tar -xzvf Catalyst.x64/angle.tar.gz
      chmod +x build_xcframework.sh
      cp build_xcframework.sh out/
      out/build_xcframework.sh
      mv out/libEGL.xcframework .
      mv out/libGLESv2.xcframework .
      tar -czvf angle.tar.gz *.xcframework
    displayName: 'Build XCFramework'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: 'angle.tar.gz'
      ArtifactName: 'XCFramework'
      publishLocation: Container
